Advanced tool tips
redcreeper14385/moundertweaks pull request #12
Opened 2020-08-30 15:29 UTC by HeyItsMeNobody

2020-08-30 16:13 UTC, BoogieMonster1O1 commented on src/main/java/mounderfod/moundertweaks/mixin/client/ItemMixin.java
> +    @Inject(method = "appendTooltip(Lnet/minecraft/item/ItemStack;Lnet/minecraft/world/World;Ljava/util/List;Lnet/minecraft/client/item/TooltipContext;)V", at = @At("HEAD"))
You don't need a mixin for this

2020-08-30 16:13 UTC, BoogieMonster1O1 commented on src/main/java/mounderfod/moundertweaks/mixin/client/ItemMixin.java
> +    // "Improved" and rewritten Shnupbups code.
Explain

2020-08-30 16:14 UTC, BoogieMonster1O1 requested changes
this is already it's own mod

2020-09-01 09:22 UTC, redcreeper14385 commented
Gonna close this for now, sorry.

2020-09-01 09:22 UTC, closed without merging